import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FormEvent } from "react";

const Home: NextPage = () => {
  const processIdRarityFetch = async (e: FormEvent<HTMLFormElement>) => {
    type IdDesired = {
      id_desired: string;
    };

    e.preventDefault();
    const data = new FormData(e.target as HTMLFormElement);
    const json = JSON.parse(JSON.stringify(Object.fromEntries(data.entries())));

    console.log(json as IdDesired);

    const response = await fetch(`/api/rarity/${json.id_desired}`);
    const resJson = await response.json();
    console.log(resJson);
  };

  return (
    <>
      <Head>
        <title>YayoCorp Rarity Viewer - BECAUSE YOU NEED TO FLEX</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="">YayoCorp Rarity Viewer</h1>
        <img
          src="https://yayo.fund/img/yayo/logo_full/logo-pink.png"
          className="h-48"
        />
        <a
          href="https://lmgtfy.app/?q=testosterone+supplements"
          className="italic"
        >
          Looking up your rarity to price accordingly? Click here!
        </a>
        <div className="mt-[200px] bg-red-500">
          <form
            onSubmit={async (e) => {
              processIdRarityFetch(e);
            }}
          >
            <label>Input ID</label>
            <input type="text" name="id_desired" />
            <button>Submit</button>
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
